"""Generate pipeline/generated/stages.yml from pipeline/arc.yaml (single workflow source)."""

from __future__ import annotations

from valeotf.arc import generated_stages_path, gitlab_stages, load_arc
from valeotf.io import dump_text, load_yaml, repo_root

HEADER = (
    "# GENERATED by `valeotf generate-ci`. Do not edit by hand.\n"
    "# Source of truth: pipeline/arc.yaml (same factory order as production).\n"
)


def stages_yaml(root: Path | None = None) -> str:
    stages = gitlab_stages(load_arc(root))
    lines = [HEADER, "stages:"]
    for stage in stages:
        lines.append(f"  - {stage}")
    lines.append("")
    return "\n".join(lines)


def write_generated_ci(root: Path | None = None) -> Path:
    path = generated_stages_path(root)
    dump_text(path, stages_yaml(root))
    return path


def assert_generated_ci(root: Path | None = None) -> None:
    root = root or repo_root()
    path = generated_stages_path(root)
    if not path.exists():
        raise ValueError(f"missing {path}; run valeotf generate-ci")
    expected = stages_yaml(root)
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        raise ValueError("pipeline/generated/stages.yml is stale. Run: valeotf generate-ci")
    ci = load_yaml(root / ".gitlab-ci.yml")
    includes = ci.get("include") or []
    texts = []
    for item in includes:
        if isinstance(item, dict) and item.get("local"):
            texts.append(item["local"])
        elif isinstance(item, str):
            texts.append(item)
    if "pipeline/generated/stages.yml" not in texts:
        raise ValueError(".gitlab-ci.yml must include pipeline/generated/stages.yml")
